### ISSUE TITLE
Have to double-click to set focus on the New Message Box.

### ISSUE THREAD

**Issue by thecodrr** [madagaga/WTalk#2]
I think the problem is here, in this part of code: `Client.cs`

```
    public void SetFocus(string conversationId)
           {
              if (conversationId.Length == 0)
              return;

        SetFocusRequest request = new SetFocusRequest()
        {
            request_header = RequestHeaderBody,
            conversation_id = new ConversationId() { id = conversationId },
            type = FocusType.FOCUS_TYPE_FOCUSED,
            timeout_secs = 20
        };

        HttpResponseMessage message = _client.PostProtoJson("conversations/setfocus", request);
        message.Dispose();
    }
```

And in this application code: `ConversationViewModel.cs`

```
   private void SetFocus()
    {

        if(this.HasUnreadMessages)
            _client.UpdateWaterMark(Conversation.Id, DateTime.UtcNow);

        _client.SetFocus(Conversation.Id);
        OnPropertyChanged("HasUnreadMessages");
    }
```

**Comment by madagaga** [comment]
even if length is 0 we have to send a set focus command. It activate the contact icon on the receiver side. Hangout client does the same.
I think the command should return something, maybe a bool, to continue

I will test your code.

Thanks

**Comment by thecodrr** [comment]
Why not use `String.Empty` in the `if` statement?

**Comment by madagaga** [comment]
☺ I don't remerber why

**Comment by thecodrr** [comment]
Well, doesn't make any difference, both are doing the same thing.

**Comment by madagaga** [comment]
MouseBinding in xaml removed.
Switch back to standard event handling.

It should be corrected

**Comment by thecodrr** [comment]
I will try and test this. I hope it works :)

**Comment by thecodrr** [comment]
It is working quite excellently, though there is a small delay before it the caret appears.
