### ISSUE TITLE
[Feature Request] Full message history

### ISSUE THREAD

**Issue by thecodrr** [madagaga/WTalk#4]
At this point, WTalk fetches only the last 10 messages I think. There should be a way to fetch last 100 messages, at least. 
I know this will clutter the application but I was thinking of the Hangouts approach. More messages are fetched as you scroll upwards. This will both keep the loading time good and the message history too.
What do you say? This feature is quite wanted.

**Comment by madagaga** [comment]
Done

**Comment by thecodrr** [comment]
It is done. Works perfectly.
