### ISSUE TITLE
Performance imporvements

### ISSUE THREAD

**Issue by thecodrr** [madagaga/WTalk#5]
I have, at the moment, only 2 conversations in Hangouts but the loading time is quite noticeable. WTalk will be overwhelmed if there are 100+ conversations, it will keep fetching the whole day.
What about implementing on-the-go strategy? I mean, loading the conversation interface as soon as first or second conversation loads or it would be better to load no conversation until it is opened and clicked by the user. This will reduce loading time significantly. 
**Only the conversation name will be loaded, and as soon as the user will click on the conversation in the conversation list, the poll request will be sent for message history.**

I will acknowledge other performance bugs as I test the application in more depth.

**Comment by thecodrr** [comment]
Have you tried using async/await when sending poll requests?

**Comment by madagaga** [comment]
The first load is synchronous, because if not, the UI would be empty.
This first request get a big response which contains session info, last active conversations.

After this, all request are async.

**Comment by thecodrr** [comment]
Right now, there is a long delay before a sent message is displayed and sometimes its not even displayed. There is also the delay when we click on the "Send Message TextBox". Also another delay when we scroll upward to get previous messages.

During the first delay, sometimes the UI becomes unresponsive.

**Comment by madagaga** [comment]
Performance (speed) is more acceptable now.
but there still some bugs, i've revamped all the code
