### ISSUE TITLE
Json parsing

### ISSUE THREAD

**Issue by madagaga** [madagaga/WTalk#7]
Sometimes json string can not be parsed.

Maybe it would be interessant to create a custom json parser.
JSON => List or Dictionary

**Comment by thecodrr** [comment]
Why not use Newtonsoft.Json?

**Comment by madagaga** [comment]
I already use Newtonsoft but, sometimes json data are not "valid" and i don't want to go deep into newtonsoft json source code and add some customization.

**Comment by madagaga** [comment]
New custom json parser
