### ISSUE TITLE
Contacts not appearing 

### ISSUE THREAD

**Issue by thecodrr** [madagaga/WTalk#8]
I think the latest commit (all requests async) is the culprit here. I tried using Async before you and I got the same results. Contacts and conversations do not appear. Though, the app works smoother.

**Comment by madagaga** [comment]
yes i've seen this bug, last commit was not complete.

**Comment by madagaga** [comment]
Now, all requests are async, and elements are loaded step by step.
Connection => Conversations => Contacts

**Comment by thecodrr** [comment]
It is now working flawlessly.

**Comment by madagaga** [comment]
Thanks for testing
