### ISSUE TITLE
One moment please...

### ISSUE THREAD

**Issue by lee-soft** [madagaga/WTalk#9]
Client is stuck on "One moment please..." whilst trying to authenticate. It gets a verification code then freezes at this stage.

**Comment by madagaga** [comment]
Thanks for you feedback.
I will take a look.

**Comment by madagaga** [comment]
Is this issue still appear after restart ?

**Comment by lee-soft** [comment]
Restarting visual studio or the computer? I've tried both. No joy

**Comment by madagaga** [comment]
Ok found, it's the 2 factor google authentication. I'll fix it .

**Comment by madagaga** [comment]
Normally it's fixed now.
